name: Release lib-ml to GitHub Packages

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Extract version
        id: vars
        run: echo "PKG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Inject version into lib_ml/__init__.py
        run: |
          sed -i "s/__version__ = .*/__version__ = \"${{ steps.vars.outputs.PKG_VERSION }}\"/" src/lib_ml/__init__.py

      - name: Build package
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Publish to GitHub Packages
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.GH_PAT }}
          repository_type: github

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_PAT }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, '-pre') }}
          files: |
            dist/*.whl
            dist/*.tar.gz
